#!/usr/bin/sh

FILE=.links.cjs
FILE_DIS=.links.temp-disabled.cjs
if test -f "$FILE_DIS"; then
  # Only do the post-commit hook if the file was temp-disabled by the pre-commit hook.
  # Otherwise linking was actively (`yarn links:disable`) disabled and this hook should noop.
  mv $FILE_DIS $FILE
  yarnLog=$(yarn)
  echo "[yarn-linker] The post-commit hook has re-enabled $FILE"
  exit 1
fi
