- name: "A-1:1"
  description: "Calls between two people"
  color: "bfd4f2"
- name: "A-Big-Grid"
  description: "The freedom layout system used for >12 participants"
  color: "bfd4f2"
- name: "A-Developer-Experience"
  description: "Workflow of developing: building, linting, debugging, profiling, etc."
  color: "c5def5"
- name: "A-E2EE"
  description: "End-to-end encryption"
  color: "bfd4f2"
- name: "A-Embedded"
  description: "Using the app embedded within other Matrix clients (as a widget)"
  color: "bfd4f2"
- name: "A-Feedback-Reporting"
  description: "Reporting process for bugs, debug logs (rageshakes), suggestions"
  color: "bfd4f2"
- name: "A-Freedom"
  description: "Freedom layout, where participants can be rearranged and resized"
  color: "bfd4f2"
- name: "A-Handset"
  description: "Audio playback through the earpiece of a phone. Also known as 'earpiece mode' or 'handset mode'."
  color: "bfd4f2"
- name: "A-Huddle"
  description: "Ad-hoc calls in a room notifying others"
  color: "bfd4f2"
- name: "A-Lobby"
  description: "The page before joining a call"
  color: "bfd4f2"
- name: "A-Login"
  color: "bfd4f2"
- name: "A-Matrix2.0"
  description: "Issues relating to the Matrix 2.0 / MSC4143 work, such as sticky events and multi-sfu"
  color: "bfd4f2"
- name: "A-Media-Devices"
  color: "BFD4F2"
- name: "A-Media-Quality"
  description: "Distortions or glitches in audio/video"
  color: "bfd4f2"
- name: "A-Meeting"
  description: "Scheduled call on the calendar"
  color: "bfd4f2"
- name: "A-Mobile"
  description: "Using the app on a mobile device"
  color: "bfd4f2"
- name: "A-Moderation"
  description: "Access to calls and powers within calls"
  color: "bfd4f2"
- name: "A-Performance"
  color: "bfd4f2"
- name: "A-Reactions"
  color: "bfd4f2"
- name: "A-Registration"
  color: "bfd4f2"
- name: "A-Screen-Sharing"
  color: "bfd4f2"
- name: "A-SDK"
  description: "SDK for building MatrixRTC + LiveKit widgets"
  color: "c5def5"
- name: "A-Settings"
  color: "bfd4f2"
- name: "A-SFU"
  description: "Routing calls through a selective forwarding unit"
  color: "bfd4f2"
- name: "A-Signaling"
  description: "Call signaling"
  color: "bfd4f2"
- name: "A-Simulcast"
  description: "Automatic selection of variable video resolutions"
  color: "bfd4f2"
- name: "A-SPA"
  description: "Standalone application accessed via call links"
  color: "bfd4f2"
- name: "A-Spatial-Audio"
  description: "Directional audio based on where a speaker appears on screen"
  color: "bfd4f2"
- name: "A-Speech-Enhancement"
  description: "Techniques to enhance the intelligibility of speech in calls"
  color: "c5def5"
- name: "A-Split-Grid"
  description: "The freedom layout system used for ≤12 participants"
  color: "bfd4f2"
- name: "A-Spotlight"
  description: "Spotlight layout, where the active speaker is foregrounded"
  color: "bfd4f2"
- name: "A-Telemetry-Posthog"
  description: "Share opt in usage data for optimizing the app via posthog"
  color: "bfd4f2"
- name: "A-Testing"
  description: "Integration tests, unit tests, etc."
  color: "bfd4f2"
- name: "A-Video-Rooms"
  description: "Rooms reserved exclusively for calling"
  color: "bfd4f2"
- name: "A-Walkie-Talkie"
  description: "Walkie-talkie / PTT (push-to-talk) mode"
  color: "bfd4f2"
- name: "A11y"
  description: "Accessibility"
  color: "4ADEC0"
- name: "backport-candidate"
  description: "Something that is a candidate for backport to a particular release branch"
  color: "0B8D85"
- name: "customer-retainer"
  color: "F44A5F"
- name: "dependencies"
  description: "Pull requests that update a dependency file"
  color: "0366d6"
- name: "development build"
  description: "runs yarn build process in development mode"
  color: "1d76db"
- name: "Discord"
  description: "Use case familiar to Discord users"
  color: "3670d2"
- name: "docker build"
  description: "Creates a docker image for this PR"
  color: "0e8a16"
- name: "EPIC"
  color: "5319E7"
- name: "good first issue"
  description: "Good for newcomers"
  color: "7057ff"
- name: "Help Wanted"
  description: "Community contributions are welcome!"
  color: "159818"
- name: "I18n"
  description: "Internationalisation"
  color: "d4c5f9"
- name: "O-Frequent"
  description: "Affects or can be seen by most users regularly or impacts most users' first experience"
  color: "0052CC"
- name: "O-Occasional"
  description: "Affects or can be seen by some users regularly or most users rarely"
  color: "1D76DB"
- name: "O-Uncommon"
  description: "Most users are unlikely to come across this or unexpected workflow"
  color: "C5DEF5"
- name: "p1"
  description: "Must fix/implement before this is usable as a product"
  color: "D93F0B"
- name: "p2"
  description: "Should fix/implement, but not at the expense of p1s"
  color: "FBCA04"
- name: "p3"
  description: "Could fix/implement when time allows"
  color: "0E8A16"
- name: "PR-Breaking-Change"
  description: "A Pull request that changes EC in a way that is incompatible to the previous version."
  color: "D93F0B"
- name: "PR-Bug-Fix"
  description: "Release note category. A PR that fixes a bug."
  color: "C2E0C6"
- name: "PR-Developer-Experience"
  description: "Release note category. A PR that does not change EC but improves working with the repository."
  color: "C2E0C6"
- name: "PR-Documentation"
  description: "Release note category. A PR that improves the documentation."
  color: "C2E0C6"
- name: "PR-Feature"
  description: "Release note category. A PR that introduces a new user facing feature."
  color: "C2E0C6"
- name: "PR-Improvement"
  description: "Release note category. A PR that improves EC's performance or stability."
  color: "C2E0C6"
- name: "PR-Task"
  description: "Release note category. A PR that is hidden from release note."
  color: "C2E0C6"
- name: "Privacy"
  color: "f41192"
- name: "Roadmap"
  color: "57457E"
- name: "S-Critical"
  description: "Prevents work, causes data loss and/or has no workaround"
  color: "bd0026"
- name: "S-Major"
  description: "Severely degrades major functionality or product features, with no satisfactory workaround"
  color: "fc4e2a"
- name: "S-Minor"
  description: "Impairs non-critical functionality or suitable workarounds exist"
  color: "feb24c"
- name: "S-Tolerable"
  description: "Low/no impact on users"
  color: "ffeda0"
- name: "Security"
  color: "b3e5fc"
- name: "storybook build"
  description: "Build and deploy the storybook frontend to netlify."
  color: "45cd61"
- name: "T-Defect"
  description: "Something isn't working: bugs, crashes, hangs, vulnerabilities, or other reported problems"
  color: "98e6ae"
- name: "T-Enhancement"
  description: "New features, changes in functionality, performance boosts, user-facing improvements"
  color: "98e6ae"
- name: "T-Other"
  description: "Questions, user support, anything else"
  color: "98e6ae"
- name: "T-Task"
  description: "Refactoring, enabling or disabling functionality, other engineering tasks"
  color: "98e6ae"
- name: "X-Blocked"
  description: "Cannot be merged due to external dependencies"
  color: "ff7979"
- name: "X-Cannot-Reproduce"
  description: "Needs reproduction steps"
  color: "ff7979"
- name: "X-Needs-Design"
  description: "May require input from the design team"
  color: "ff7979"
- name: "X-Needs-Info"
  description: "This issue is blocked awaiting information from the reporter"
  color: "ff7979"
- name: "X-Needs-Investigation"
  color: "ff7979"
- name: "X-Needs-Product"
  description: "More input needed from the Product team"
  color: "ff7979"
- name: "X-Regression"
  color: "ff7979"
- name: "X-Release-Blocker"
  color: "ff7979"
- name: "X-Spec-Changes"
  description: "May require spec changes"
  color: "ff7979"
- name: "X-Won't-Fix"
  description: "This will not be worked on"
  color: "ff7979"
- name: "Z-Community-Testing"
  description: "Issues found during the community testing sessions"
  color: "efefef"
- name: "Z-Could"
  color: "ededed"
- name: "Z-Design"
  color: "ededed"
- name: "Z-Flaky-Test"
  color: "aaaaaa"
- name: "Z-Media-Failure"
  description: "Someone's audio or video isn't coming through"
  color: "ededed"
- name: "Z-Must"
  color: "ededed"
- name: "Z-Platform-Specific"
  color: "ededed"
- name: "Z-Power-Users"
  color: "ededed"
- name: "Z-ProductPolish"
  color: "aaaaaa"
- name: "Z-Should"
  color: "ededed"
- name: "Z-Splitbrain"
  description: "Someone who should be on the call isn't showing up"
  color: "ededed"
