name: Lint, format & type check
on:
  pull_request: {}
jobs:
  prettier:
    name: Lint, format & type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Enable Corepack
        run: corepack enable
      - name: Yarn cache
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          cache: "yarn"
          node-version-file: ".node-version"
      - name: Install dependencies
        run: "yarn install --immutable"
      - name: Prettier
        run: "yarn run prettier:check"
      - name: i18n
        run: "yarn run i18n:check"
      - name: ESLint
        run: "yarn run lint:eslint"
      - name: Type check
        run: "yarn run lint:types"
      - name: Dead code analysis
        run: "yarn run lint:knip"
