name: Build & publish full packages for releases

on:
  release:
    types: [published]

jobs:
  build_element_call:
    uses: ./.github/workflows/build-element-call.yaml
    with:
      package: full
      vite_app_version: ${{ github.event.release.tag_name }}
    secrets:
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  publish_tarball:
    needs: build_element_call
    if: always()
    name: Publish tarball
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to upload release asset
      packages: write
    steps:
      - name: 📥 Download built element-call artifact
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id || github.run_id }}
          name: build-output-full
          path: dist
      - name: Create Tarball
        env:
          TARBALL_VERSION: ${{ github.event.release.tag_name }}
        run: |
          tar --numeric-owner --transform "s/dist/element-call-${TARBALL_VERSION}/" -cvzf element-call-${TARBALL_VERSION}.tar.gz dist
          sha256sum element-call-${TARBALL_VERSION}.tar.gz | tee element-call-${TARBALL_VERSION}.tar.gz.sha256
      - name: Upload
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: |
            element-call-${{ github.event.release.tag_name }}.tar.gz
            element-call-${{ github.event.release.tag_name }}.tar.gz.sha256

  publish_docker:
    needs: build_element_call
    if: always()
    name: Publish docker
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/build-and-publish-docker.yaml
    with:
      artifact_run_id: ${{ github.event.workflow_run.id || github.run_id }}
      docker_tags: |
        type=sha,format=short,event=branch
        type=semver,pattern=v{{version}}
  add_docker_release_note:
    needs: publish_docker
    name: Add docker release note
    runs-on: ubuntu-latest
    steps:
      - name: Add release note
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          body: |
            ## Docker
            Element Call is available as a Docker image from the [GitHub Container Registry](https://github.com/element-hq/element-call/pkgs/container/element-call).

            The image provides a full build of Element Call that can be used both in standalone and as a widget.

            ```
            docker pull ghcr.io/element-hq/element-call:${{ github.event.release.tag_name }}
            ```
